### ISSUE TITLE
Methods continuedについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/Go4#3]
#Methods continued

struct型のメソッドは何となくわかりました。
Methods are functionsについても
```gof
func (v Vertex) Abs() float64
```
は
```gof
func Abs(v Vertex) float64 
```
でも通常の関数でも記述可能と理解しました。

優先順位でもあったMethods continuedで数値型の MyFloat 型がわかりません。
数値型の MyFloat 型のサンプルコードお願いします。

**Comment by totsumaru** [comment]
基本的にはこのような使い方はほとんどしませんので、大丈夫です。
ただ、stringやint、float64など、あらかじめ名前が決まっている型もtype Name stringのようにすることで、string型に「Name型」という名前を付けることができます。
自分で名前をつけた型は、メソッドにすることができます。

```go
package main

import (
	"fmt"
)

type Name string // Name型（実際はstringだけど、Name型という型の名前をつけた）

// Name構造体のメソッドです
// ただのstring型だとメソッドにできませんが、Name型にしたことでメソッドが作成できる
func (n Name) HelloName() string {
	return fmt.Sprintf("Hello! %s", n)
}

func main() {
	n := Name("Taro") // Name型を作成

	fmt.Println(n.HelloName()) // Hello! Taro
}
```
